### ISSUE TITLE
Download does not start on Firefox

### ISSUE THREAD

**Issue by fffiloni** [WenheLI/p5.gif#10]
**Describe the bug**
Download will never start on Firefox (on Windows and MacOS)

**To Reproduce**

1.Try it on Firefox

**Expected behavior**
Download should be triggered, like it is on Safari and Chrome.

**Comment by WenheLI** [comment]
fix by commit 9e2c45d1d52a5113df7a5149167ac87954c43ceb
Please use the latest link [https://unpkg.com/p5.gif@1.0.2-rc1/dist/p5gif.min.js](https://unpkg.com/p5.gif@1.0.2-rc1/dist/p5gif.min.js)
