### ISSUE TITLE
Generate a loopin gif on download ?

### ISSUE THREAD

**Issue by fffiloni** [WenheLI/p5.gif#11]
Hello !

The GIFs generated are not looping by default on export.

How could we be able to set this property in the config object  ?

**Comment by WenheLI** [comment]
The feature of exporting a looping gif is not supposed yet. Hopefully, it will be ready before this weekend!

**Comment by WenheLI** [comment]
@fffiloni You can download a loop gif right now.
```js=
  recorder = p5Gif.capture({framerate: 60, repeat: true});
```
Be sure to set the repeat as true when you init capture.

**Comment by infusion** [comment]
Could you add a note on the wiki for this behavior? Thanks!

**Comment by WenheLI** [comment]
@infusion Added on the wiki, thanks for pointing out this!
