### ISSUE TITLE
Broken CDN link

### ISSUE THREAD

**Issue by infusion** [WenheLI/p5.gif#15]
Hello,

when using p5.gif via the link https://p5gif.s3.yuu.uno/stable/p5gif.min.js an SSL protocol error is reported.

Robert

**Comment by WenheLI** [comment]
Hi,
We have moved our CDN to unpkg right now. So you should import in this way.
```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.7.2/p5.min.js"></script>
<script src="https://unpkg.com/p5.gif@1.0.5/dist/p5gif.min.js"></script>
```
Could you please tell me, where did you found the old cdn link? I am gonna get rid of the old link.

**Comment by infusion** [comment]
Yep, I changed to unpkg. I found it here: https://github.com/WenheLI/p5.gif/wiki

**Comment by WenheLI** [comment]
Thanks!
