### ISSUE TITLE
Custom GIF FPS export

### ISSUE THREAD

**Issue by fffiloni** [WenheLI/p5.gif#16]
**Is your feature request related to a problem? Please describe.**
I think i'm confused by the word `framerate` used in the recorder settings. If i'm right, the framerate settings has control on which frame from the canvas framerate are added in the recorder for creating a gif. 

**Describe the solution you'd like**
What i need is to be able to **control also the framerate of the gif itself**, when we open it in a browser.

**Additional context**
The context is that, i don't use the p5 framerate to render the canvas, i add manually each frame i want to be processed as part of the animated gif. When i then trigger download, i want the gif to set a delay between frame, customized by the user (4, 8, 12 or 24) 

Thanks for your help

**Comment by WenheLI** [comment]
@fffiloni You are right about the framerate. Now you can set the framerate as you want! 
Be sure to use the latest version which is 1.0.6
https://unpkg.com/p5.gif@1.0.6/dist/p5gif.min.js
Fix by e11f4026c604b90dfa2aecc2c71b505993faad5c
