### ISSUE TITLE
start() yields this.stopAfter error

### ISSUE THREAD

**Issue by shiffman** [WenheLI/p5.gif#5]
Tested this in the p5.js web editor (see: https://editor.p5js.org/icm/sketches/rkQeIbi0m)

```javascript
let gif;

function setup() {
  createCanvas(400, 400);
  gif = p5Gif.capture();
  gif.start();
}
```
Error: `Uncaught TypeError: this.stopAfter is not a function (sketch: line 8)`

**Comment by D31F43** [comment]
get fixed in 7422d8ce71912cf20c3c4773776faf8f9bf85f26
