### ISSUE TITLE
custom filename?

### ISSUE THREAD

**Issue by shiffman** [WenheLI/p5.gif#6]
I'm calling

```javascript
    recorder.download('codingtrain.gif');
```

But the file is still named "default.gif". Perhaps I'm setting the filename the incorrect way?

Full code: https://editor.p5js.org/codingtrain/sketches/WfEih8mL7

**Comment by WenheLI** [comment]
This problem is probably because of caching a wrong version of the library file. The temporary solution is to download the file from the [release](https://github.com/WenheLI/p5.gif/releases)  and manually import it into your project.

**Comment by WenheLI** [comment]
Custom filename solved. Please use the least cdn.
